### ISSUE TITLE
Баг с кириллической у

### ISSUE THREAD

**Issue by Sirogap** [feerus23/Makisans#5]
В полужирной версии вместо прописной (маленькой) кириллической "у" стоит сочетание "ту".
![image](https://github.com/feerus23/MakiSans/assets/141056352/8da3dec3-cff1-4ffb-acba-4074e4feac4f)

Ну и над прописной кириллической "г" еще б поработать, что-то она не в строю...

**Comment by svrfee** [comment]
В общем я решил по новой перерисовать и в новой версии попытаюсь все сделать по уму. Спасибо за критику.
